POST http://localhost:5001/create/mytest

###

POST http://localhost:5001/write/mytest
Content-Type: application/text

message1
message2
message3
message4
message5

###

GET http://localhost:5001/read/mytest?base64=true
Content-Type: application/x-ndjson

###

GET http://localhost:5001/read/mytest?base64=false
Content-Type: application/x-ndjson

