// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ibsen.proto

package github.com.tcw.ibsen.client;

public interface EmptyArgsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EmptyArgs)
    com.google.protobuf.MessageOrBuilder {
}
