// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ibsen.proto

package github.com.tcw.ibsen.client;

public interface EntryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Entry)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 offset = 1;</code>
   * @return The offset.
   */
  long getOffset();

  /**
   * <code>bytes content = 2;</code>
   * @return The content.
   */
  com.google.protobuf.ByteString getContent();
}
