// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ibsen.proto

package github.com.tcw.ibsen.client;

public final class IbsenProto {
  private IbsenProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmptyArgs_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EmptyArgs_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WriteStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WriteStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReadParams_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReadParams_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_InputEntries_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_InputEntries_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TopicList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TopicList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Entry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Entry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OutputEntries_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OutputEntries_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013ibsen.proto\"\013\n\tEmptyArgs\"\034\n\013WriteStatu" +
      "s\022\r\n\005wrote\030\001 \001(\003\"X\n\nReadParams\022\r\n\005topic\030" +
      "\001 \001(\t\022\016\n\006offset\030\002 \001(\004\022\021\n\tbatchSize\030\003 \001(\r" +
      "\022\030\n\020stopOnCompletion\030\004 \001(\010\".\n\014InputEntri" +
      "es\022\r\n\005topic\030\001 \001(\t\022\017\n\007entries\030\002 \003(\014\"\033\n\tTo" +
      "picList\022\016\n\006topics\030\001 \003(\t\"(\n\005Entry\022\016\n\006offs" +
      "et\030\001 \001(\004\022\017\n\007content\030\002 \001(\014\"(\n\rOutputEntri" +
      "es\022\027\n\007entries\030\002 \003(\0132\006.Entry2z\n\005Ibsen\022&\n\005" +
      "write\022\r.InputEntries\032\014.WriteStatus\"\000\022\'\n\004" +
      "read\022\013.ReadParams\032\016.OutputEntries\"\0000\001\022 \n" +
      "\004list\022\n.EmptyArgs\032\n.TopicList\"\000BA\n\033githu" +
      "b.com.tcw.ibsen.clientB\nIbsenProtoP\001Z\014/a" +
      "pi/grpcApi\242\002\005IBSENb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_EmptyArgs_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_EmptyArgs_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EmptyArgs_descriptor,
        new java.lang.String[] { });
    internal_static_WriteStatus_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_WriteStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WriteStatus_descriptor,
        new java.lang.String[] { "Wrote", });
    internal_static_ReadParams_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ReadParams_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReadParams_descriptor,
        new java.lang.String[] { "Topic", "Offset", "BatchSize", "StopOnCompletion", });
    internal_static_InputEntries_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_InputEntries_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_InputEntries_descriptor,
        new java.lang.String[] { "Topic", "Entries", });
    internal_static_TopicList_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_TopicList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TopicList_descriptor,
        new java.lang.String[] { "Topics", });
    internal_static_Entry_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_Entry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Entry_descriptor,
        new java.lang.String[] { "Offset", "Content", });
    internal_static_OutputEntries_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_OutputEntries_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OutputEntries_descriptor,
        new java.lang.String[] { "Entries", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
