// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ibsen.proto

package github.com.tcw.ibsen.client;

public interface InputEntriesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:InputEntries)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string topic = 1;</code>
   * @return The topic.
   */
  java.lang.String getTopic();
  /**
   * <code>string topic = 1;</code>
   * @return The bytes for topic.
   */
  com.google.protobuf.ByteString
      getTopicBytes();

  /**
   * <code>repeated bytes entries = 2;</code>
   * @return A list containing the entries.
   */
  java.util.List<com.google.protobuf.ByteString> getEntriesList();
  /**
   * <code>repeated bytes entries = 2;</code>
   * @return The count of entries.
   */
  int getEntriesCount();
  /**
   * <code>repeated bytes entries = 2;</code>
   * @param index The index of the element to return.
   * @return The entries at the given index.
   */
  com.google.protobuf.ByteString getEntries(int index);
}
