// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ibsen.proto

package github.com.tcw.ibsen.client;

public interface OutputEntriesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OutputEntries)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Entry entries = 2;</code>
   */
  java.util.List<github.com.tcw.ibsen.client.Entry> 
      getEntriesList();
  /**
   * <code>repeated .Entry entries = 2;</code>
   */
  github.com.tcw.ibsen.client.Entry getEntries(int index);
  /**
   * <code>repeated .Entry entries = 2;</code>
   */
  int getEntriesCount();
  /**
   * <code>repeated .Entry entries = 2;</code>
   */
  java.util.List<? extends github.com.tcw.ibsen.client.EntryOrBuilder> 
      getEntriesOrBuilderList();
  /**
   * <code>repeated .Entry entries = 2;</code>
   */
  github.com.tcw.ibsen.client.EntryOrBuilder getEntriesOrBuilder(
      int index);
}
