// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ibsen.proto

package github.com.tcw.ibsen.client;

public interface ReadParamsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ReadParams)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string topic = 1;</code>
   * @return The topic.
   */
  java.lang.String getTopic();
  /**
   * <code>string topic = 1;</code>
   * @return The bytes for topic.
   */
  com.google.protobuf.ByteString
      getTopicBytes();

  /**
   * <code>uint64 offset = 2;</code>
   * @return The offset.
   */
  long getOffset();

  /**
   * <code>uint32 batchSize = 3;</code>
   * @return The batchSize.
   */
  int getBatchSize();

  /**
   * <code>bool stopOnCompletion = 4;</code>
   * @return The stopOnCompletion.
   */
  boolean getStopOnCompletion();
}
