// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ibsen.proto

package github.com.tcw.ibsen.client;

/**
 * Protobuf type {@code TopicList}
 */
public final class TopicList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:TopicList)
    TopicListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TopicList.newBuilder() to construct.
  private TopicList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TopicList() {
    topics_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TopicList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TopicList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              topics_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            topics_.add(s);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        topics_ = topics_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return github.com.tcw.ibsen.client.IbsenProto.internal_static_TopicList_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return github.com.tcw.ibsen.client.IbsenProto.internal_static_TopicList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            github.com.tcw.ibsen.client.TopicList.class, github.com.tcw.ibsen.client.TopicList.Builder.class);
  }

  public static final int TOPICS_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList topics_;
  /**
   * <code>repeated string topics = 1;</code>
   * @return A list containing the topics.
   */
  public com.google.protobuf.ProtocolStringList
      getTopicsList() {
    return topics_;
  }
  /**
   * <code>repeated string topics = 1;</code>
   * @return The count of topics.
   */
  public int getTopicsCount() {
    return topics_.size();
  }
  /**
   * <code>repeated string topics = 1;</code>
   * @param index The index of the element to return.
   * @return The topics at the given index.
   */
  public java.lang.String getTopics(int index) {
    return topics_.get(index);
  }
  /**
   * <code>repeated string topics = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the topics at the given index.
   */
  public com.google.protobuf.ByteString
      getTopicsBytes(int index) {
    return topics_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < topics_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, topics_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < topics_.size(); i++) {
        dataSize += computeStringSizeNoTag(topics_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getTopicsList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof github.com.tcw.ibsen.client.TopicList)) {
      return super.equals(obj);
    }
    github.com.tcw.ibsen.client.TopicList other = (github.com.tcw.ibsen.client.TopicList) obj;

    if (!getTopicsList()
        .equals(other.getTopicsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getTopicsCount() > 0) {
      hash = (37 * hash) + TOPICS_FIELD_NUMBER;
      hash = (53 * hash) + getTopicsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static github.com.tcw.ibsen.client.TopicList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static github.com.tcw.ibsen.client.TopicList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static github.com.tcw.ibsen.client.TopicList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static github.com.tcw.ibsen.client.TopicList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static github.com.tcw.ibsen.client.TopicList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static github.com.tcw.ibsen.client.TopicList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static github.com.tcw.ibsen.client.TopicList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static github.com.tcw.ibsen.client.TopicList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static github.com.tcw.ibsen.client.TopicList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static github.com.tcw.ibsen.client.TopicList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static github.com.tcw.ibsen.client.TopicList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static github.com.tcw.ibsen.client.TopicList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(github.com.tcw.ibsen.client.TopicList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code TopicList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:TopicList)
      github.com.tcw.ibsen.client.TopicListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return github.com.tcw.ibsen.client.IbsenProto.internal_static_TopicList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return github.com.tcw.ibsen.client.IbsenProto.internal_static_TopicList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              github.com.tcw.ibsen.client.TopicList.class, github.com.tcw.ibsen.client.TopicList.Builder.class);
    }

    // Construct using github.com.tcw.ibsen.client.TopicList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      topics_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return github.com.tcw.ibsen.client.IbsenProto.internal_static_TopicList_descriptor;
    }

    @java.lang.Override
    public github.com.tcw.ibsen.client.TopicList getDefaultInstanceForType() {
      return github.com.tcw.ibsen.client.TopicList.getDefaultInstance();
    }

    @java.lang.Override
    public github.com.tcw.ibsen.client.TopicList build() {
      github.com.tcw.ibsen.client.TopicList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public github.com.tcw.ibsen.client.TopicList buildPartial() {
      github.com.tcw.ibsen.client.TopicList result = new github.com.tcw.ibsen.client.TopicList(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) != 0)) {
        topics_ = topics_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.topics_ = topics_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof github.com.tcw.ibsen.client.TopicList) {
        return mergeFrom((github.com.tcw.ibsen.client.TopicList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(github.com.tcw.ibsen.client.TopicList other) {
      if (other == github.com.tcw.ibsen.client.TopicList.getDefaultInstance()) return this;
      if (!other.topics_.isEmpty()) {
        if (topics_.isEmpty()) {
          topics_ = other.topics_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureTopicsIsMutable();
          topics_.addAll(other.topics_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      github.com.tcw.ibsen.client.TopicList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (github.com.tcw.ibsen.client.TopicList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList topics_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureTopicsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        topics_ = new com.google.protobuf.LazyStringArrayList(topics_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string topics = 1;</code>
     * @return A list containing the topics.
     */
    public com.google.protobuf.ProtocolStringList
        getTopicsList() {
      return topics_.getUnmodifiableView();
    }
    /**
     * <code>repeated string topics = 1;</code>
     * @return The count of topics.
     */
    public int getTopicsCount() {
      return topics_.size();
    }
    /**
     * <code>repeated string topics = 1;</code>
     * @param index The index of the element to return.
     * @return The topics at the given index.
     */
    public java.lang.String getTopics(int index) {
      return topics_.get(index);
    }
    /**
     * <code>repeated string topics = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the topics at the given index.
     */
    public com.google.protobuf.ByteString
        getTopicsBytes(int index) {
      return topics_.getByteString(index);
    }
    /**
     * <code>repeated string topics = 1;</code>
     * @param index The index to set the value at.
     * @param value The topics to set.
     * @return This builder for chaining.
     */
    public Builder setTopics(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureTopicsIsMutable();
      topics_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string topics = 1;</code>
     * @param value The topics to add.
     * @return This builder for chaining.
     */
    public Builder addTopics(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureTopicsIsMutable();
      topics_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string topics = 1;</code>
     * @param values The topics to add.
     * @return This builder for chaining.
     */
    public Builder addAllTopics(
        java.lang.Iterable<java.lang.String> values) {
      ensureTopicsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, topics_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string topics = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTopics() {
      topics_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string topics = 1;</code>
     * @param value The bytes of the topics to add.
     * @return This builder for chaining.
     */
    public Builder addTopicsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureTopicsIsMutable();
      topics_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:TopicList)
  }

  // @@protoc_insertion_point(class_scope:TopicList)
  private static final github.com.tcw.ibsen.client.TopicList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new github.com.tcw.ibsen.client.TopicList();
  }

  public static github.com.tcw.ibsen.client.TopicList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TopicList>
      PARSER = new com.google.protobuf.AbstractParser<TopicList>() {
    @java.lang.Override
    public TopicList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TopicList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TopicList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TopicList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public github.com.tcw.ibsen.client.TopicList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

