// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ibsen.proto

package github.com.tcw.ibsen.client;

public interface TopicListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TopicList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string topics = 1;</code>
   * @return A list containing the topics.
   */
  java.util.List<java.lang.String>
      getTopicsList();
  /**
   * <code>repeated string topics = 1;</code>
   * @return The count of topics.
   */
  int getTopicsCount();
  /**
   * <code>repeated string topics = 1;</code>
   * @param index The index of the element to return.
   * @return The topics at the given index.
   */
  java.lang.String getTopics(int index);
  /**
   * <code>repeated string topics = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the topics at the given index.
   */
  com.google.protobuf.ByteString
      getTopicsBytes(int index);
}
