// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ibsen.proto

package github.com.tcw.ibsen.client;

public interface WriteStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WriteStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 wrote = 1;</code>
   * @return The wrote.
   */
  long getWrote();
}
