// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ibsen.proto

package grpcApi

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type WriteStatus struct {
	Wrote                int64    `protobuf:"varint,1,opt,name=wrote,proto3" json:"wrote,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WriteStatus) Reset()         { *m = WriteStatus{} }
func (m *WriteStatus) String() string { return proto.CompactTextString(m) }
func (*WriteStatus) ProtoMessage()    {}
func (*WriteStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_c3e5c14afe4be539, []int{0}
}

func (m *WriteStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteStatus.Unmarshal(m, b)
}
func (m *WriteStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteStatus.Marshal(b, m, deterministic)
}
func (m *WriteStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteStatus.Merge(m, src)
}
func (m *WriteStatus) XXX_Size() int {
	return xxx_messageInfo_WriteStatus.Size(m)
}
func (m *WriteStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteStatus.DiscardUnknown(m)
}

var xxx_messageInfo_WriteStatus proto.InternalMessageInfo

func (m *WriteStatus) GetWrote() int64 {
	if m != nil {
		return m.Wrote
	}
	return 0
}

type ReadParams struct {
	Topic                string   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Offset               uint64   `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	BatchSize            uint32   `protobuf:"varint,3,opt,name=batchSize,proto3" json:"batchSize,omitempty"`
	StopOnCompletion     bool     `protobuf:"varint,4,opt,name=stopOnCompletion,proto3" json:"stopOnCompletion,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadParams) Reset()         { *m = ReadParams{} }
func (m *ReadParams) String() string { return proto.CompactTextString(m) }
func (*ReadParams) ProtoMessage()    {}
func (*ReadParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_c3e5c14afe4be539, []int{1}
}

func (m *ReadParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadParams.Unmarshal(m, b)
}
func (m *ReadParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadParams.Marshal(b, m, deterministic)
}
func (m *ReadParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadParams.Merge(m, src)
}
func (m *ReadParams) XXX_Size() int {
	return xxx_messageInfo_ReadParams.Size(m)
}
func (m *ReadParams) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadParams.DiscardUnknown(m)
}

var xxx_messageInfo_ReadParams proto.InternalMessageInfo

func (m *ReadParams) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *ReadParams) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ReadParams) GetBatchSize() uint32 {
	if m != nil {
		return m.BatchSize
	}
	return 0
}

func (m *ReadParams) GetStopOnCompletion() bool {
	if m != nil {
		return m.StopOnCompletion
	}
	return false
}

type InputEntries struct {
	Topic                string   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Entries              [][]byte `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InputEntries) Reset()         { *m = InputEntries{} }
func (m *InputEntries) String() string { return proto.CompactTextString(m) }
func (*InputEntries) ProtoMessage()    {}
func (*InputEntries) Descriptor() ([]byte, []int) {
	return fileDescriptor_c3e5c14afe4be539, []int{2}
}

func (m *InputEntries) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InputEntries.Unmarshal(m, b)
}
func (m *InputEntries) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InputEntries.Marshal(b, m, deterministic)
}
func (m *InputEntries) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InputEntries.Merge(m, src)
}
func (m *InputEntries) XXX_Size() int {
	return xxx_messageInfo_InputEntries.Size(m)
}
func (m *InputEntries) XXX_DiscardUnknown() {
	xxx_messageInfo_InputEntries.DiscardUnknown(m)
}

var xxx_messageInfo_InputEntries proto.InternalMessageInfo

func (m *InputEntries) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *InputEntries) GetEntries() [][]byte {
	if m != nil {
		return m.Entries
	}
	return nil
}

type TopicList struct {
	Topics               []string `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TopicList) Reset()         { *m = TopicList{} }
func (m *TopicList) String() string { return proto.CompactTextString(m) }
func (*TopicList) ProtoMessage()    {}
func (*TopicList) Descriptor() ([]byte, []int) {
	return fileDescriptor_c3e5c14afe4be539, []int{3}
}

func (m *TopicList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopicList.Unmarshal(m, b)
}
func (m *TopicList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopicList.Marshal(b, m, deterministic)
}
func (m *TopicList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopicList.Merge(m, src)
}
func (m *TopicList) XXX_Size() int {
	return xxx_messageInfo_TopicList.Size(m)
}
func (m *TopicList) XXX_DiscardUnknown() {
	xxx_messageInfo_TopicList.DiscardUnknown(m)
}

var xxx_messageInfo_TopicList proto.InternalMessageInfo

func (m *TopicList) GetTopics() []string {
	if m != nil {
		return m.Topics
	}
	return nil
}

type Entry struct {
	Offset               uint64   `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Content              []byte   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Entry) Reset()         { *m = Entry{} }
func (m *Entry) String() string { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()    {}
func (*Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_c3e5c14afe4be539, []int{4}
}

func (m *Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entry.Unmarshal(m, b)
}
func (m *Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entry.Marshal(b, m, deterministic)
}
func (m *Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entry.Merge(m, src)
}
func (m *Entry) XXX_Size() int {
	return xxx_messageInfo_Entry.Size(m)
}
func (m *Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_Entry proto.InternalMessageInfo

func (m *Entry) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *Entry) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type OutputEntries struct {
	Entries              []*Entry `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OutputEntries) Reset()         { *m = OutputEntries{} }
func (m *OutputEntries) String() string { return proto.CompactTextString(m) }
func (*OutputEntries) ProtoMessage()    {}
func (*OutputEntries) Descriptor() ([]byte, []int) {
	return fileDescriptor_c3e5c14afe4be539, []int{5}
}

func (m *OutputEntries) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutputEntries.Unmarshal(m, b)
}
func (m *OutputEntries) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutputEntries.Marshal(b, m, deterministic)
}
func (m *OutputEntries) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutputEntries.Merge(m, src)
}
func (m *OutputEntries) XXX_Size() int {
	return xxx_messageInfo_OutputEntries.Size(m)
}
func (m *OutputEntries) XXX_DiscardUnknown() {
	xxx_messageInfo_OutputEntries.DiscardUnknown(m)
}

var xxx_messageInfo_OutputEntries proto.InternalMessageInfo

func (m *OutputEntries) GetEntries() []*Entry {
	if m != nil {
		return m.Entries
	}
	return nil
}

func init() {
	proto.RegisterType((*WriteStatus)(nil), "WriteStatus")
	proto.RegisterType((*ReadParams)(nil), "ReadParams")
	proto.RegisterType((*InputEntries)(nil), "InputEntries")
	proto.RegisterType((*TopicList)(nil), "TopicList")
	proto.RegisterType((*Entry)(nil), "Entry")
	proto.RegisterType((*OutputEntries)(nil), "OutputEntries")
}

func init() { proto.RegisterFile("ibsen.proto", fileDescriptor_c3e5c14afe4be539) }

var fileDescriptor_c3e5c14afe4be539 = []byte{
	// 401 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x5f, 0x8b, 0xd3, 0x40,
	0x14, 0xc5, 0x3b, 0xfd, 0xb7, 0xe6, 0x26, 0x15, 0x19, 0x16, 0x19, 0xa2, 0x0f, 0x61, 0x16, 0x34,
	0x88, 0x4c, 0x74, 0x7d, 0xd2, 0x07, 0xc1, 0x4a, 0x1f, 0x0a, 0xe2, 0x96, 0xa9, 0x20, 0xf8, 0x96,
	0x64, 0xa7, 0xd9, 0x81, 0x26, 0x33, 0x24, 0x37, 0x2c, 0xeb, 0xb3, 0xf8, 0x41, 0xfc, 0xa4, 0x92,
	0xc9, 0x76, 0x9b, 0x22, 0x3e, 0xfe, 0x6e, 0x4e, 0x6e, 0xce, 0xb9, 0x27, 0xe0, 0xeb, 0xac, 0x51,
	0x95, 0xb0, 0xb5, 0x41, 0x13, 0x3e, 0x2b, 0x8c, 0x29, 0xf6, 0x2a, 0x71, 0x94, 0xb5, 0xbb, 0x44,
	0x95, 0x16, 0xef, 0xfa, 0x87, 0xfc, 0x02, 0xfc, 0xef, 0xb5, 0x46, 0xb5, 0xc5, 0x14, 0xdb, 0x86,
	0x9e, 0xc3, 0xec, 0xb6, 0x36, 0xa8, 0x18, 0x89, 0x48, 0x3c, 0x91, 0x3d, 0xf0, 0x5f, 0x04, 0x40,
	0xaa, 0xf4, 0x7a, 0x93, 0xd6, 0x69, 0xe9, 0x44, 0x68, 0xac, 0xce, 0x9d, 0xc8, 0x93, 0x3d, 0xd0,
	0xa7, 0x30, 0x37, 0xbb, 0x5d, 0xa3, 0x90, 0x8d, 0x23, 0x12, 0x4f, 0xe5, 0x3d, 0xd1, 0xe7, 0xe0,
	0x65, 0x29, 0xe6, 0x37, 0x5b, 0xfd, 0x53, 0xb1, 0x49, 0x44, 0xe2, 0x85, 0x3c, 0x0e, 0xe8, 0x2b,
	0x78, 0xd2, 0xa0, 0xb1, 0x57, 0xd5, 0x67, 0x53, 0xda, 0xbd, 0x42, 0x6d, 0x2a, 0x36, 0x8d, 0x48,
	0xfc, 0x48, 0xfe, 0x33, 0xe7, 0x1f, 0x21, 0x58, 0x57, 0xb6, 0xc5, 0x55, 0x85, 0xb5, 0x56, 0xff,
	0xf3, 0xc1, 0xe0, 0x4c, 0xf5, 0x02, 0x36, 0x8e, 0x26, 0x71, 0x20, 0x0f, 0xc8, 0x2f, 0xc0, 0xfb,
	0xd6, 0x49, 0xbe, 0xe8, 0x06, 0x3b, 0xbb, 0x4e, 0xdf, 0x30, 0x12, 0x4d, 0x62, 0x4f, 0xde, 0x13,
	0x7f, 0x0f, 0xb3, 0x6e, 0xff, 0xdd, 0x20, 0x0f, 0x39, 0xc9, 0xc3, 0xe0, 0x2c, 0x37, 0x15, 0xaa,
	0xaa, 0x0f, 0x1a, 0xc8, 0x03, 0xf2, 0xb7, 0xb0, 0xb8, 0x6a, 0x71, 0x60, 0x30, 0x3a, 0xb5, 0xe2,
	0x5f, 0xce, 0x85, 0xdb, 0xfd, 0x60, 0xe9, 0xf2, 0x37, 0x81, 0xd9, 0xba, 0xeb, 0x8a, 0xbe, 0xe8,
	0x2e, 0xaf, 0x51, 0xd1, 0x85, 0x18, 0x86, 0x0c, 0x03, 0x31, 0xe8, 0x87, 0x8f, 0xe8, 0x4b, 0x98,
	0xd6, 0x2a, 0xbd, 0xa6, 0xbe, 0x38, 0x36, 0x12, 0x3e, 0x16, 0x27, 0x1f, 0xe6, 0xa3, 0x37, 0x84,
	0xbe, 0x86, 0xe9, 0xde, 0x05, 0x15, 0x7d, 0xff, 0xe2, 0xd0, 0xbf, 0x58, 0x75, 0xfd, 0x87, 0x20,
	0x1e, 0x8e, 0xc1, 0x47, 0xcb, 0x0f, 0x70, 0x5e, 0x68, 0xbc, 0x69, 0x33, 0x91, 0x9b, 0x52, 0x60,
	0x7e, 0x2b, 0xdc, 0x2f, 0xb4, 0x04, 0xe7, 0x6e, 0xd3, 0xbd, 0xba, 0x21, 0x3f, 0x82, 0x24, 0xb5,
	0x3a, 0x29, 0x6a, 0x9b, 0x7f, 0xb2, 0xfa, 0xcf, 0x78, 0xb6, 0x5e, 0x6e, 0x57, 0x5f, 0xb3, 0xb9,
	0xdb, 0xfc, 0xee, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5b, 0x28, 0x69, 0x6a, 0x76, 0x02, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// IbsenClient is the client API for Ibsen service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IbsenClient interface {
	Write(ctx context.Context, in *InputEntries, opts ...grpc.CallOption) (*WriteStatus, error)
	Read(ctx context.Context, in *ReadParams, opts ...grpc.CallOption) (Ibsen_ReadClient, error)
	List(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*TopicList, error)
}

type ibsenClient struct {
	cc grpc.ClientConnInterface
}

func NewIbsenClient(cc grpc.ClientConnInterface) IbsenClient {
	return &ibsenClient{cc}
}

func (c *ibsenClient) Write(ctx context.Context, in *InputEntries, opts ...grpc.CallOption) (*WriteStatus, error) {
	out := new(WriteStatus)
	err := c.cc.Invoke(ctx, "/Ibsen/write", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ibsenClient) Read(ctx context.Context, in *ReadParams, opts ...grpc.CallOption) (Ibsen_ReadClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Ibsen_serviceDesc.Streams[0], "/Ibsen/read", opts...)
	if err != nil {
		return nil, err
	}
	x := &ibsenReadClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Ibsen_ReadClient interface {
	Recv() (*OutputEntries, error)
	grpc.ClientStream
}

type ibsenReadClient struct {
	grpc.ClientStream
}

func (x *ibsenReadClient) Recv() (*OutputEntries, error) {
	m := new(OutputEntries)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *ibsenClient) List(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*TopicList, error) {
	out := new(TopicList)
	err := c.cc.Invoke(ctx, "/Ibsen/list", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IbsenServer is the server API for Ibsen service.
type IbsenServer interface {
	Write(context.Context, *InputEntries) (*WriteStatus, error)
	Read(*ReadParams, Ibsen_ReadServer) error
	List(context.Context, *empty.Empty) (*TopicList, error)
}

// UnimplementedIbsenServer can be embedded to have forward compatible implementations.
type UnimplementedIbsenServer struct {
}

func (*UnimplementedIbsenServer) Write(ctx context.Context, req *InputEntries) (*WriteStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Write not implemented")
}
func (*UnimplementedIbsenServer) Read(req *ReadParams, srv Ibsen_ReadServer) error {
	return status.Errorf(codes.Unimplemented, "method Read not implemented")
}
func (*UnimplementedIbsenServer) List(ctx context.Context, req *empty.Empty) (*TopicList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}

func RegisterIbsenServer(s *grpc.Server, srv IbsenServer) {
	s.RegisterService(&_Ibsen_serviceDesc, srv)
}

func _Ibsen_Write_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InputEntries)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IbsenServer).Write(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Ibsen/Write",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IbsenServer).Write(ctx, req.(*InputEntries))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ibsen_Read_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadParams)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(IbsenServer).Read(m, &ibsenReadServer{stream})
}

type Ibsen_ReadServer interface {
	Send(*OutputEntries) error
	grpc.ServerStream
}

type ibsenReadServer struct {
	grpc.ServerStream
}

func (x *ibsenReadServer) Send(m *OutputEntries) error {
	return x.ServerStream.SendMsg(m)
}

func _Ibsen_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IbsenServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Ibsen/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IbsenServer).List(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Ibsen_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Ibsen",
	HandlerType: (*IbsenServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "write",
			Handler:    _Ibsen_Write_Handler,
		},
		{
			MethodName: "list",
			Handler:    _Ibsen_List_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "read",
			Handler:       _Ibsen_Read_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ibsen.proto",
}
