// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.12.4
// source: ibsen.proto

package grpcApi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmptyArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyArgs) Reset() {
	*x = EmptyArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ibsen_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyArgs) ProtoMessage() {}

func (x *EmptyArgs) ProtoReflect() protoreflect.Message {
	mi := &file_ibsen_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyArgs.ProtoReflect.Descriptor instead.
func (*EmptyArgs) Descriptor() ([]byte, []int) {
	return file_ibsen_proto_rawDescGZIP(), []int{0}
}

type WriteStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Wrote int64 `protobuf:"varint,1,opt,name=wrote,proto3" json:"wrote,omitempty"`
}

func (x *WriteStatus) Reset() {
	*x = WriteStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ibsen_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteStatus) ProtoMessage() {}

func (x *WriteStatus) ProtoReflect() protoreflect.Message {
	mi := &file_ibsen_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteStatus.ProtoReflect.Descriptor instead.
func (*WriteStatus) Descriptor() ([]byte, []int) {
	return file_ibsen_proto_rawDescGZIP(), []int{1}
}

func (x *WriteStatus) GetWrote() int64 {
	if x != nil {
		return x.Wrote
	}
	return 0
}

type ReadParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Topic            string `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Offset           uint64 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	BatchSize        uint32 `protobuf:"varint,3,opt,name=batchSize,proto3" json:"batchSize,omitempty"`
	StopOnCompletion bool   `protobuf:"varint,4,opt,name=stopOnCompletion,proto3" json:"stopOnCompletion,omitempty"`
}

func (x *ReadParams) Reset() {
	*x = ReadParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ibsen_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadParams) ProtoMessage() {}

func (x *ReadParams) ProtoReflect() protoreflect.Message {
	mi := &file_ibsen_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadParams.ProtoReflect.Descriptor instead.
func (*ReadParams) Descriptor() ([]byte, []int) {
	return file_ibsen_proto_rawDescGZIP(), []int{2}
}

func (x *ReadParams) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *ReadParams) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ReadParams) GetBatchSize() uint32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

func (x *ReadParams) GetStopOnCompletion() bool {
	if x != nil {
		return x.StopOnCompletion
	}
	return false
}

type InputEntries struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Topic   string   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Entries [][]byte `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
}

func (x *InputEntries) Reset() {
	*x = InputEntries{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ibsen_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InputEntries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputEntries) ProtoMessage() {}

func (x *InputEntries) ProtoReflect() protoreflect.Message {
	mi := &file_ibsen_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputEntries.ProtoReflect.Descriptor instead.
func (*InputEntries) Descriptor() ([]byte, []int) {
	return file_ibsen_proto_rawDescGZIP(), []int{3}
}

func (x *InputEntries) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *InputEntries) GetEntries() [][]byte {
	if x != nil {
		return x.Entries
	}
	return nil
}

type TopicList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Topics []string `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"`
}

func (x *TopicList) Reset() {
	*x = TopicList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ibsen_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopicList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicList) ProtoMessage() {}

func (x *TopicList) ProtoReflect() protoreflect.Message {
	mi := &file_ibsen_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicList.ProtoReflect.Descriptor instead.
func (*TopicList) Descriptor() ([]byte, []int) {
	return file_ibsen_proto_rawDescGZIP(), []int{4}
}

func (x *TopicList) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

type Entry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offset  uint64 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Content []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *Entry) Reset() {
	*x = Entry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ibsen_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_ibsen_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_ibsen_proto_rawDescGZIP(), []int{5}
}

func (x *Entry) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *Entry) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type OutputEntries struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries []*Entry `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
}

func (x *OutputEntries) Reset() {
	*x = OutputEntries{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ibsen_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OutputEntries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputEntries) ProtoMessage() {}

func (x *OutputEntries) ProtoReflect() protoreflect.Message {
	mi := &file_ibsen_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputEntries.ProtoReflect.Descriptor instead.
func (*OutputEntries) Descriptor() ([]byte, []int) {
	return file_ibsen_proto_rawDescGZIP(), []int{6}
}

func (x *OutputEntries) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_ibsen_proto protoreflect.FileDescriptor

var file_ibsen_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x69, 0x62, 0x73, 0x65, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x0b, 0x0a,
	0x09, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x41, 0x72, 0x67, 0x73, 0x22, 0x23, 0x0a, 0x0b, 0x57, 0x72,
	0x69, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x72, 0x6f,
	0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x77, 0x72, 0x6f, 0x74, 0x65, 0x22,
	0x84, 0x01, 0x0a, 0x0a, 0x52, 0x65, 0x61, 0x64, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x6f, 0x70, 0x69, 0x63, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x1c, 0x0a, 0x09,
	0x62, 0x61, 0x74, 0x63, 0x68, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x09, 0x62, 0x61, 0x74, 0x63, 0x68, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x2a, 0x0a, 0x10, 0x73, 0x74,
	0x6f, 0x70, 0x4f, 0x6e, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x10, 0x73, 0x74, 0x6f, 0x70, 0x4f, 0x6e, 0x43, 0x6f, 0x6d, 0x70,
	0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x3e, 0x0a, 0x0c, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x45,
	0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x18, 0x0a, 0x07,
	0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x07, 0x65,
	0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x22, 0x23, 0x0a, 0x09, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x06, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x73, 0x22, 0x39, 0x0a, 0x05, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x31, 0x0a, 0x0d, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74,
	0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x12, 0x20, 0x0a, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69,
	0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x32, 0x7a, 0x0a, 0x05, 0x49, 0x62, 0x73,
	0x65, 0x6e, 0x12, 0x26, 0x0a, 0x05, 0x77, 0x72, 0x69, 0x74, 0x65, 0x12, 0x0d, 0x2e, 0x49, 0x6e,
	0x70, 0x75, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x1a, 0x0c, 0x2e, 0x57, 0x72, 0x69,
	0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x00, 0x12, 0x27, 0x0a, 0x04, 0x72, 0x65,
	0x61, 0x64, 0x12, 0x0b, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x1a,
	0x0e, 0x2e, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x22,
	0x00, 0x30, 0x01, 0x12, 0x20, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x0a, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x41, 0x72, 0x67, 0x73, 0x1a, 0x0a, 0x2e, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x4c,
	0x69, 0x73, 0x74, 0x22, 0x00, 0x42, 0x41, 0x0a, 0x1b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2e, 0x74, 0x63, 0x77, 0x2e, 0x69, 0x62, 0x73, 0x65, 0x6e, 0x2e, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x42, 0x0a, 0x49, 0x62, 0x73, 0x65, 0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x50, 0x01, 0x5a, 0x0c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x41, 0x70, 0x69,
	0xa2, 0x02, 0x05, 0x49, 0x42, 0x53, 0x45, 0x4e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ibsen_proto_rawDescOnce sync.Once
	file_ibsen_proto_rawDescData = file_ibsen_proto_rawDesc
)

func file_ibsen_proto_rawDescGZIP() []byte {
	file_ibsen_proto_rawDescOnce.Do(func() {
		file_ibsen_proto_rawDescData = protoimpl.X.CompressGZIP(file_ibsen_proto_rawDescData)
	})
	return file_ibsen_proto_rawDescData
}

var file_ibsen_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_ibsen_proto_goTypes = []interface{}{
	(*EmptyArgs)(nil),     // 0: EmptyArgs
	(*WriteStatus)(nil),   // 1: WriteStatus
	(*ReadParams)(nil),    // 2: ReadParams
	(*InputEntries)(nil),  // 3: InputEntries
	(*TopicList)(nil),     // 4: TopicList
	(*Entry)(nil),         // 5: Entry
	(*OutputEntries)(nil), // 6: OutputEntries
}
var file_ibsen_proto_depIdxs = []int32{
	5, // 0: OutputEntries.entries:type_name -> Entry
	3, // 1: Ibsen.write:input_type -> InputEntries
	2, // 2: Ibsen.read:input_type -> ReadParams
	0, // 3: Ibsen.list:input_type -> EmptyArgs
	1, // 4: Ibsen.write:output_type -> WriteStatus
	6, // 5: Ibsen.read:output_type -> OutputEntries
	4, // 6: Ibsen.list:output_type -> TopicList
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ibsen_proto_init() }
func file_ibsen_proto_init() {
	if File_ibsen_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ibsen_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ibsen_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ibsen_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ibsen_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InputEntries); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ibsen_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopicList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ibsen_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Entry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ibsen_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OutputEntries); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ibsen_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ibsen_proto_goTypes,
		DependencyIndexes: file_ibsen_proto_depIdxs,
		MessageInfos:      file_ibsen_proto_msgTypes,
	}.Build()
	File_ibsen_proto = out.File
	file_ibsen_proto_rawDesc = nil
	file_ibsen_proto_goTypes = nil
	file_ibsen_proto_depIdxs = nil
}
